version: '3.7'

networks:
  achicgi-test:
    driver: bridge

services:
  #################################
  ### SETUP POSTGRESQL CONTAINER
  #################################
  db:
    image: postgres:13.3-alpine
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER: 
      POSTGRES_DB: 
    # ports:
    #   - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks: 
      - achicgi-test

  ##############################
  ### SETUP BACKEND
  ##############################
  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: backend
    environment: 
      DB_TYPE: 
      DB_HOST: 
      DB_PORT: 
      DB_USERNAME: 
      DB_PASSWORD: 
      DB_DATABASE: 
      DB_ENTITIES: dist/**/*.entity{.ts,.js}
      DB_SYNCHRONIZE: 'true'
      DB_LOGGING_BOOLEAN: 'true'
    ports:
      - "3000:3000"
    volumes: 
      - ./src:/usr/src/app
    networks: 
      - achicgi-test
    depends_on: 
      - db