version: '3.7'

networks:
  achicgi:
    driver: bridge

services:
  #################################
  ### SETUP POSTGRESQL CONTAINER
  #################################
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: achicgi
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks: 
      - achicgi

  ##############################
  ### SETUP BACKEND
  ##############################
  # backend:
  #   build:
  #     context: .
  #     dockerfile: dev.Dockerfile
  #   container_name: backend
  #   volumes: 
  #     - ./src:/usr/src/app
  #   networks: 
  #     - achicgi
  #   depends_on: 
  #     - db