version: '3.7'

networks:
  achicgi-dev:
    driver: bridge

services:
  #################################
  ### SETUP POSTGRESQL CONTAINER
  #################################
  db:
    image: postgres:13.3-alpine
    restart: always
    container_name: db
    env_file:
      - .env
    # ports:
    #   - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks: 
      - achicgi-dev

  ##############################
  ### SETUP BACKEND
  ##############################
  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes: 
      - ./src:/usr/src/app
    networks: 
      - achicgi-dev
    depends_on: 
      - db
