version: '3.7'

networks:
  achicgi-prod:
    driver: bridge

services:
  #################################
  ### SETUP POSTGRESQL CONTAINER
  #################################
  db:
    image: postgres:13.3-alpine
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: achicgi-prod
    # ports:
    #   - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks: 
      - achicgi-prod

  ##############################
  ### SETUP BACKEND
  ##############################
  backend:
    build:
      context: .
      dockerfile: prod.Dockerfile
    container_name: backend
    environment: 
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: '5432'
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: achicgi
      DB_ENTITIES: dist/**/*.entity{.ts,.js}
      DB_SYNCHRONIZE: 'true'
      DB_LOGGING_BOOLEAN: 'true'
    ports:
      - "3000:3000"
    volumes: 
      - ./src:/usr/src/app
    networks: 
      - achicgi-prod
    depends_on: 
      - db